# # version: '3'
# services:
#   bkashbd.eu:
#     build:
#       context: .
#       dockerfile: .docker/Dockerfile
#     image: bkashbd.eu
#     ports:
#       - 8052:80
#     volumes:
#       - .:/var/www
#     links:
#       - mysql
#       - redis
#     environment:
#       DB_HOST: mysql
#       DB_DATABASE: mfs
#       DB_USERNAME: root
#       DB_PASSWORD: password
#     depends_on:
#       - mysql
#       - redis

# mysql:
#   image: mysql:8
#   container_name: mysql_bkashbd.eu
#   ports:
#     - "3306:3306"
#   command: --default-authentication-plugin=mysql_native_password
#   environment:
#     MYSQL_DATABASE: mfs
#     MYSQL_USER: user
#     MYSQL_PASSWORD: password
#     MYSQL_ROOT_PASSWORD: password
#   volumes:
#     - mysql_data:/var/lib/mysql

# volumes:
#   mysql_data:

#   ##ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'root';
#   #ALTER USER 'root'@'%' IDENTIFIED WITH mysql_native_password BY 'root';
#   #ALTER USER 'default'@'%' IDENTIFIED WITH mysql_native_password BY 'secret';
#   ##
#   phpmyadmin:
#     image: phpmyadmin/phpmyadmin:latest
#     environment:
#       - PMA_ARBITRARY=1
#       - TESTSUITE_PASSWORD=password
#       - PMA_HOSTS=mysql
#       - PMA_USER=root
#       - PMA_PASSWORD=password
#     restart: always
#     ports:
#       - 8080:80
#     volumes:
#       - /sessions
#     links:
#       - mysql
#     depends_on:
#       - mysql

#   redis:
#     image: redis:3.2-alpine


version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    image: bkashbd.eu
    container_name: bkash_app
    ports:
      - "8052:8052"
    volumes:
      - .:/var/www
    environment:
      DB_HOST: mysql
      DB_DATABASE: bkashdb
      DB_USERNAME: root
      DB_PASSWORD: rootpassword
    depends_on:
      - mysql
      - redis

  mysql:
    image: mysql:8.0
    container_name: mysql_bkash
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: bkashdb
      MYSQL_USER: bkashuser
      MYSQL_PASSWORD: secret
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin_bkash
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: rootpassword
    depends_on:
      - mysql

  redis:
    image: redis:3.2-alpine
    container_name: redis_bkash
    restart: always

volumes:
  mysql_data:
