name: bkashbd_eu
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.3.8
  http: 0.13.4
  path: 1.8.0
  get_storage: 2.0.3
  intl: 0.17.0
  backdrop: ^0.6.2
  dropdown_search: ^2.0.1
  package_info_plus: ^1.3.0
  url_launcher: ^6.0.17
  flutter:
    sdk: flutter
  share: ^2.0.4
  collection: ^1.15.0
  cached_network_image: ^3.2.0

dev_dependencies:
  flutter_lints: ^1.0.0
  lints: 1.0.1
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/
  fonts:
    - family: Exo
      fonts:
        - asset: assets/fonts/Exo/Exo-VariableFont_wght.ttf
  uses-material-design: true

